test_that("report function work properly", {
  report <- mreport(battles)
  column <- c("Battle", "Date", "Parties")
  type <- c("character", "mdate", "character")
  missing <- c(0, 0, 0)
  missingp <- c(0, 0, 0)
  min <- c("NA", "2001-03-08", "BD-ID")
  max <- c("NA", "2002-01-03", "NA")
  names(type) <- c("Battle", "Date", "Parties")
  names(missing) <- c("Battle", "Date", "Parties")
  names(missingp) <- c("Battle", "Date", "Parties")
  names(min) <- c("Battle", "Date", "Parties")
  names(max) <- c("Battle", "Date", "Parties")
  expect_s3_class(mreport(battles), "mreport")
  expect_equal(report$Rows, 20)
  expect_equal(report$Columns, 3)
  expect_equal(report$Variables, column)
  expect_equal(report$Types, type)
  expect_equal(report$Missing, missing)
  expect_equal(report$MissingPer, missingp)
  expect_equal(report$Minv, min)
  expect_equal(report$Maxv, max)
  expect_length(mreport(battles), 9)
})
